version: "3.9"

services:
  db:
    image: postgres:15
    container_name: automation_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: automation_db
    ports:
      - "5432:5432"
